name : Protecting the main branch
on:
   pull_request:
    branches:
        - main
jobs:
    test:
        runs-on : ubuntu-latest
        steps:
            - name : Checkout
              uses : actions/checkout@v2
            - name : Set up node
              uses : actions/setup-node@v1
              with:
                  node-version : '18.x'
            - name : Install Dependencies
              run : npm install
            - name : Run Tests
              run : npm run test 


